Repository playframework/play-json, pull requests merged in 2019-05, with the labels that each got.

#216 Make Writes typeclass invariant
  .jvmopts
  play-json/jvm/src/main/scala/play/api/libs/json/EnvWrites.scala
  play-json/shared/src/main/scala/play/api/libs/json/JsConstraints.scala
  play-json/shared/src/main/scala/play/api/libs/json/JsMacroImpl.scala
  play-json/shared/src/main/scala/play/api/libs/json/Writes.scala
  play-json/shared/src/test/scala/play/api/libs/json/MacroSpec.scala
  play-json/shared/src/test/scala/play/api/libs/json/TupleSpec.scala
Labels: status:backlog

#275 Target Java 8 in the build
  build.sbt
Labels: status:needs-backport, topic:build/tests

#277 Avoid passing -target to javadoc
  build.sbt
Labels: status:needs-backport
